import Head from "next/head";
import Link from "next/link";

export async function getStaticProps() {
  const data = await fetch("https://fakestoreapi.com/products?limit=10").then(
    (resp) => resp.json()
  );

  return {
    props: {
      data,
    },
    revalidate: 10,
  };
}

export default function Home({ data }: any) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Products</h1>
        <div className="productsContainer">
          {data.map((item: any) => (
            <Link href={`/${item.id}`}>
              <div className="productContainer" key={item.id}>
                <h1>{item.title}</h1>
                <p>{item.description}</p>
                <p>{item.category}</p>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
