import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

let pageNumber = 1;
const urlData = `https://api.coingecko.com/api/v3/exchanges/?per_page=100&page=${pageNumber}`;

export async function getStaticProps() {
  const criptoData = await fetch(urlData).then((resp) => resp.json());

  return {
    props: {
      criptoData,
    },
  };
}

export default function Home({ criptoData }: any) {
  console.log(criptoData);
  return (
    <>
      <Head>
        <title>Lista de CriptoMoedas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.buttonsDiv}>
          <button>Página Anterior</button>
          <button>Próxima Página</button>
        </div>

        <div className={styles.searchDiv}>
          <input type="text" placeholder="Filtrar por nome" />
        </div>

        <div className={styles.summaryDiv}>
          <h4>Exibindo x de y</h4>
        </div>

        <ul className={styles.itemsContainer}>
          {criptoData.map((item: any) => (
            <li>
              <div className={styles.imageNameContainer}>
                <Image
                  src={item.image}
                  alt={item.name}
                  width={40}
                  height={40}
                />
                <h3>{item.name}</h3>
              </div>

              <p>Ano de criação: {item.year_established}</p>
              <p>País: {item.country}</p>
              <p>Pontuação: {item.trust_score}</p>
              <p>
                Volume de trade (24 horas):{" "}
                {item.trade_volume_24h_btc.toFixed(2)}
              </p>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
